### PR TITLE
Class load added

### PR DESCRIPTION
**Pull request by AfonsoCostaVale**

### CODE REVIEW

**Comment by AfonsoCostaVale** [comment]
Waiting to solve this issue https://github.com/JoaoAlmeida-dev/ADS_Project_3_Group11/issues/4 to be merged

**Comment by AfonsoCostaVale** [comment]
I think outside in the static load method that we will create for each DTO

**Comment by JoaoAlmeida-dev** [comment]
Ok, then i think we can merge

**Comment by AfonsoCostaVale** [comment]
[Data load - Class](https://trello.com/c/VU0RCm1J/10-data-load-class)

**Pull request merged**
